[build]
  command = "npm run build"  # Build the Sanity Studio
  publish = "dist"  # Folder where Sanity Studio will be built

[build.environment]
  SANITY_PROJECT_ID = "7qflttjf"
  SANITY_DATASET = "production"

[[redirects]]
  from = "/sanity/*"
  to = "/sanity/index.html"
  status = 200
